
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-2
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-2
pull_requests: [{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-CapacityPerUser","number":32,"title":"RG - Added CapacityPerUser field to Commons Edit/Create/List Page (pt. 1 of Issue #8)","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/32"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-Commons-UI-Defaults","number":31,"title":"JZ - UX FIX: Default values on Create Commons Form","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/31"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-Commons-UI-CreateCommonsForm","number":30,"title":"JZ- UX FIX: Make fields narrower on Create Commons Form","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/30"},{"author":{"id":"MDQ6VXNlcjc3NzEwNjU5","is_bot":false,"login":"cyrus895","name":""},"headRefName":"CC-FeatureRemovePurchasePopups","number":27,"title":"CC - removed purchase pop ups","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/27"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-sell-cow","number":26,"title":"ka - makes unhealthy cows cheaper to sell","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/26"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-delete-warning","number":23,"title":"ka - adds a warning window popping up upon attempting to delete a commons","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/23"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-BackButton","number":21,"title":"RG - Leaderboard Back Button + Tests","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/21"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-Commons-Feature-Degradation","number":17,"title":"JZ- Commons Feature modified to allow degradation values to be set as low as 0.001 (steps)","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/17"}]
