
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-2
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-delete-warning","number":23,"title":"ka - adds a warning window popping up upon attempting to delete a commons","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/23"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-timezones","number":22,"title":"ka - fixes the timezone for Milk and Health scheduled jobs","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/22"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-BackButton","number":21,"title":"RG - Leaderboard Back Button + Tests","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/21"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-Commons-Feature-Degradation","number":17,"title":"JZ- Commons Feature modified to allow degradation values to be set as low as 0.001 (steps)","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/17"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-Leaderboard-Feature-Wealth","number":16,"title":"JZ -  added Leaderboard Feature for totalWealth to be displayed in the desired format","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/16"}]
