
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-2
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-2
pull_requests: [{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-EffectiveCapacity3","number":59,"title":"RG - EffectiveCapacity Part 2","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/59"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-EffectiveCapacity2","number":58,"title":"Rocky effective capacity2","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/58"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-CommonStats-Frontend-Feature","number":57,"title":"JZ - CommonStats frontend modifying CommonsTable + tests","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/57"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-UpdateCowHealth","number":50,"title":"RG - Part 3 of Issue #8; effectiveCapacity Now Is Used In Formulas","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/50"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-EffectiveCapacity","number":49,"title":"RG - Part 2 of Issue #8; added effectiveCapacity that shows up on frontend; does not affect Health Formulas yet.","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/49"}]
