
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-2
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-update-stryker-mutation-testing","number":62,"title":"pc - only do stryker mutation testing on changed frontend file","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/62"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-effectiveCapacity","number":61,"title":"ka - reimplements effectiveCapacity issue","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/61"}]
