
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-2
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-2
pull_requests: [{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-CommonStats-Jobs","number":52,"title":"Josh common stats jobs","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/52"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-UpdateCowHealth","number":50,"title":"RG - Part 3 of Issue #8; effectiveCapacity Now Is Used In Formulas","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/50"},{"author":{"id":"U_kgDOBXyOow","is_bot":false,"login":"rockygao2020","name":"Rocky Gao"},"headRefName":"Rocky-EffectiveCapacity","number":49,"title":"RG - Part 2 of Issue #8; added effectiveCapacity that shows up on frontend; does not affect Health Formulas yet.","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/49"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-restrict_jobs_to_live_commons","number":48,"title":"ka - makes automatic jobs only run on in-progress commons","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/48"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-CommonStats-Endpoint","number":45,"title":"JZ CommonStats endpoint ","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/45"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-CommonStats","number":36,"title":"JZ - CommonStats","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/36"},{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"ka-lastdayDate","number":34,"title":"ka - a new Last Day Date entry (setting the end date of a game) + gameInProgress() function telling whether the game is ongoing","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-2/pull/34"}]
